// generated by newgenasym  Wed Sep 18 13:42:47 2019


module u_usb_hub_rts5489 (\5v_in1 , \5v_in2 , \5v_ldo , adc_cap, adc_in0, adc_in1, av10_1,
        av10_10, av10_2, av10_3, av10_4, av10_5, av10_6, av10_7,
        av10_8, av10_9, av33_1, av33_2, av33_3, bpwr_det, dsp1_d_n,
        dsp1_d_p, dsp1_ocp, dsp1_pwr_en, dsp1_rx_n, dsp1_rx_p,
        dsp1_tx_n, dsp1_tx_p, dsp2_d_n, dsp2_d_p, dsp2_ocp,
        dsp2_pwr_en, dsp2_rx_n, dsp2_rx_p, dsp2_tx_n, dsp2_tx_p,
        dsp3_d_n, dsp3_d_p, dsp3_ocp, dsp3_pwr_en, dsp3_rx_n,
        dsp3_rx_p, dsp3_tx_n, dsp3_tx_p, dsp4_d_n, dsp4_d_p,
        dsp4_ocp, dsp4_pwr_en, dsp4_rx_n, dsp4_rx_p, dsp4_tx_n,
        dsp4_tx_p, epad, gnd1, gnd2, gnd3, gpio14, i2c_clk, i2c_dat,
        \i2c_int* , loc_pwr, nc1, nc10, nc11, nc12, nc2, nc3, nc4, nc5,
        nc6, nc7, nc8, nc9, rref, sm_clk, sm_dat, \sm_int* , spi_miso,
        spi_mosi, spi_sck, spi_scs_n, usp_d_n, usp_d_p, usp_rx_n,
        usp_rx_p, usp_tx_n, usp_tx_p, xtli, xtlo);
    input \5v_in1 ;
    input \5v_in2 ;
    input \5v_ldo ;
    input adc_cap;
    inout adc_in0;
    inout adc_in1;
    input av10_1;
    input av10_10;
    input av10_2;
    input av10_3;
    input av10_4;
    input av10_5;
    input av10_6;
    input av10_7;
    input av10_8;
    input av10_9;
    input av33_1;
    input av33_2;
    input av33_3;
    input bpwr_det;
    inout dsp1_d_n;
    inout dsp1_d_p;
    inout dsp1_ocp;
    inout dsp1_pwr_en;
    input dsp1_rx_n;
    input dsp1_rx_p;
    output dsp1_tx_n;
    output dsp1_tx_p;
    inout dsp2_d_n;
    inout dsp2_d_p;
    inout dsp2_ocp;
    inout dsp2_pwr_en;
    input dsp2_rx_n;
    input dsp2_rx_p;
    output dsp2_tx_n;
    output dsp2_tx_p;
    inout dsp3_d_n;
    inout dsp3_d_p;
    inout dsp3_ocp;
    inout dsp3_pwr_en;
    input dsp3_rx_n;
    input dsp3_rx_p;
    output dsp3_tx_n;
    output dsp3_tx_p;
    inout dsp4_d_n;
    inout dsp4_d_p;
    inout dsp4_ocp;
    inout dsp4_pwr_en;
    input dsp4_rx_n;
    input dsp4_rx_p;
    output dsp4_tx_n;
    output dsp4_tx_p;
    input epad;
    input gnd1;
    input gnd2;
    input gnd3;
    inout gpio14;
    inout i2c_clk;
    inout i2c_dat;
    inout \i2c_int* ;
    input loc_pwr;
    input nc1;
    inout nc10;
    inout nc11;
    inout nc12;
    input nc2;
    input nc3;
    input nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout nc9;
    input rref;
    inout sm_clk;
    inout sm_dat;
    inout \sm_int* ;
    inout spi_miso;
    inout spi_mosi;
    inout spi_sck;
    inout spi_scs_n;
    inout usp_d_n;
    inout usp_d_p;
    input usp_rx_n;
    input usp_rx_p;
    output usp_tx_n;
    output usp_tx_p;
    input xtli;
    output xtlo;


    initial
        begin
        end

endmodule
