// generated by newgenasym  Tue Apr 08 18:02:09 2014


module q_npn (b, b1, b2, c, c1, c2, e, e1, e2);
    inout b;
    inout b1;
    inout b2;
    inout c;
    inout c1;
    inout c2;
    inout e;
    inout e1;
    inout e2;


    initial
        begin
        end

endmodule
