-- generated by newgenasym Tue Apr 08 18:02:09 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity q_npn is
    port (    
	B:         INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC;    
	E1:        INOUT  STD_LOGIC;    
	E2:        INOUT  STD_LOGIC);
end q_npn;
