// generated by newgenasym  Sat Apr 05 12:56:53 2014


module q_fet_p_enh (d, d1, d1a, d1b, d2, d2a, d2b, d3, d4, d5, g, g1, g2, s, s1, s1_a,
        s1_b, s2, s2_a, s2_b, s3, sa, sb);
    inout d;
    inout d1;
    inout d1a;
    inout d1b;
    inout d2;
    inout d2a;
    inout d2b;
    inout d3;
    inout d4;
    inout d5;
    inout g;
    inout g1;
    inout g2;
    inout s;
    inout s1;
    inout s1_a;
    inout s1_b;
    inout s2;
    inout s2_a;
    inout s2_b;
    inout s3;
    inout sa;
    inout sb;


    initial
        begin
        end

endmodule
