-- generated by newgenasym Sat Apr 05 12:56:53 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity q_fet_p_enh is
    port (    
	D:         INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D1A:       INOUT  STD_LOGIC;    
	D1B:       INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D2A:       INOUT  STD_LOGIC;    
	D2B:       INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	D4:        INOUT  STD_LOGIC;    
	D5:        INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	G1:        INOUT  STD_LOGIC;    
	G2:        INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	S1_A:      INOUT  STD_LOGIC;    
	S1_B:      INOUT  STD_LOGIC;    
	S2:        INOUT  STD_LOGIC;    
	S2_A:      INOUT  STD_LOGIC;    
	S2_B:      INOUT  STD_LOGIC;    
	S3:        INOUT  STD_LOGIC;    
	SA:        INOUT  STD_LOGIC;    
	SB:        INOUT  STD_LOGIC);
end q_fet_p_enh;
