// generated by newgenasym  Mon Sep 09 14:19:56 2019


module u_sw_load (bat, ct, en, ep, gnd, in, in1, in2, jig, \oc* , on, on_k, on_off,
        out, r1_c1, r2, s_en, ta, tpad, vbias, vin, vin1, vin2, vin3,
        vina, vinb, vout, vout1, vout2, vout3, vouta, voutb);
    input bat;
    inout ct;
    input en;
    input ep;
    input gnd;
    input in;
    input in1;
    input in2;
    input jig;
    output \oc* ;
    input on;
    input on_k;
    inout on_off;
    input out;
    inout r1_c1;
    inout r2;
    input s_en;
    input ta;
    input tpad;
    input vbias;
    input vin;
    input vin1;
    input vin2;
    input vin3;
    input vina;
    input vinb;
    input vout;
    input vout1;
    input vout2;
    input vout3;
    input vouta;
    input voutb;


    initial
        begin
        end

endmodule
