-- generated by newgenasym Mon Sep 09 14:19:56 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_sw_load is
    port (    
	BAT:       IN     STD_LOGIC;    
	CT:        INOUT  STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	IN1:       IN     STD_LOGIC;    
	IN2:       IN     STD_LOGIC;    
	JIG:       IN     STD_LOGIC;    
	\oc*\:     OUT    STD_LOGIC;    
	\on\:      IN     STD_LOGIC;    
	ON_K:      IN     STD_LOGIC;    
	ON_OFF:    INOUT  STD_LOGIC;    
	\out\:     IN     STD_LOGIC;    
	R1_C1:     INOUT  STD_LOGIC;    
	R2:        INOUT  STD_LOGIC;    
	S_EN:      IN     STD_LOGIC;    
	TA:        IN     STD_LOGIC;    
	TPAD:      IN     STD_LOGIC;    
	VBIAS:     IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VIN1:      IN     STD_LOGIC;    
	VIN2:      IN     STD_LOGIC;    
	VIN3:      IN     STD_LOGIC;    
	VINA:      IN     STD_LOGIC;    
	VINB:      IN     STD_LOGIC;    
	VOUT:      IN     STD_LOGIC;    
	VOUT1:     IN     STD_LOGIC;    
	VOUT2:     IN     STD_LOGIC;    
	VOUT3:     IN     STD_LOGIC;    
	VOUTA:     IN     STD_LOGIC;    
	VOUTB:     IN     STD_LOGIC);
end u_sw_load;
