-- generated by newgenasym Thu Jan 08 10:56:19 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_levshft_txb0108 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	B5:        INOUT  STD_LOGIC;    
	B6:        INOUT  STD_LOGIC;    
	B7:        INOUT  STD_LOGIC;    
	B8:        INOUT  STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	VCCA:      IN     STD_LOGIC;    
	VCCB:      IN     STD_LOGIC);
end u_levshft_txb0108;
