// generated by newgenasym  Tue Oct 17 20:03:40 2017


module hdr_1x12 (\1 , \10 , \11 , \12 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 , mnt1, mnt2);
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout mnt1;
    inout mnt2;


    initial
        begin
        end

endmodule
