-- generated by newgenasym Thu Jul 17 17:30:57 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_buf_od is
    port (    
	A:         INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	Y:         INOUT  STD_LOGIC);
end u_buf_od;
