// generated by newgenasym  Mon Sep 22 14:11:08 2008


module xtal_4pin (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
