-- generated by newgenasym Mon Sep 22 14:11:08 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity XTAL_4PIN is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end XTAL_4PIN;
