// generated by newgenasym  Tue May 22 16:11:22 2007


module hdr_1x2 (\1 , \2 , mnt1, mnt2);
    inout \1 ;
    inout \2 ;
    inout mnt1;
    inout mnt2;


    initial
        begin
        end

endmodule
