-- generated by newgenasym Tue May 22 16:11:22 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HDR_1X2 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	MNT1:      INOUT  STD_LOGIC;    
	MNT2:      INOUT  STD_LOGIC);
end HDR_1X2;
