// generated by newgenasym  Fri Jun 12 12:36:47 2015


module u_mem_fl_ser_512kx8 (clk, \cs* , dio, do, gnd, gndp, \hold* , sck, si, so, vcc, \wp* );
    input clk;
    input \cs* ;
    inout dio;
    output do;
    input gnd;
    input gndp;
    input \hold* ;
    input sck;
    inout si;
    output so;
    input vcc;
    input \wp* ;


    initial
        begin
        end

endmodule
