-- generated by newgenasym Fri Jun 12 12:36:47 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_mem_fl_ser_512kx8 is
    port (    
	CLK:       IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	DIO:       INOUT  STD_LOGIC;    
	DO:        OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	GNDP:      IN     STD_LOGIC;    
	\hold*\:   IN     STD_LOGIC;    
	SCK:       IN     STD_LOGIC;    
	SI:        INOUT  STD_LOGIC;    
	SO:        OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\wp*\:     IN     STD_LOGIC);
end u_mem_fl_ser_512kx8;
