// generated by newgenasym  Mon Mar 25 22:32:30 2013


module l_cmf_4p (\1 , \2 , \3 , \4 , p1, p2, p3, p4);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout p1;
    inout p2;
    inout p3;
    inout p4;


    initial
        begin
        end

endmodule
