-- generated by newgenasym Mon Mar 25 22:32:30 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l_cmf_4p is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	P4:        INOUT  STD_LOGIC);
end l_cmf_4p;
