// generated by newgenasym  Tue Mar 06 14:14:26 2018


module hdr_1x4 (\1 , \10 , \12v , \2 , \3 , \4 , \5 , \5v , \6 , \7 , \8 , \9 , gnd, gnd1, gnd2, mt1, mt2,
        pwm, pwm_out, strap1, strap2, tach, tach_in);
    inout \1 ;
    inout \10 ;
    inout \12v ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \5v ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout gnd;
    inout gnd1;
    inout gnd2;
    inout mt1;
    inout mt2;
    inout pwm;
    inout pwm_out;
    inout strap1;
    inout strap2;
    inout tach;
    inout tach_in;


    initial
        begin
        end

endmodule
