-- generated by newgenasym Tue Mar 06 14:14:26 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hdr_1x4 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\10\:      INOUT  STD_LOGIC;    
	\12v\:     INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\5v\:      INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	MT1:       INOUT  STD_LOGIC;    
	MT2:       INOUT  STD_LOGIC;    
	PWM:       INOUT  STD_LOGIC;    
	PWM_OUT:   INOUT  STD_LOGIC;    
	STRAP1:    INOUT  STD_LOGIC;    
	STRAP2:    INOUT  STD_LOGIC;    
	TACH:      INOUT  STD_LOGIC;    
	TACH_IN:   INOUT  STD_LOGIC);
end hdr_1x4;
