// generated by newgenasym  Tue Jun 25 12:44:34 2019


module con_rj45 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 , ch_gnd,
        ch_gnd0, ch_gnd1, com, ct0, ct1, ct2, ct3, ct4, d1_led,
        d1_led0, d1_led1, d2_led, d2_led0, d2_led1, d3_led, d3_led0,
        d3_led1, d4_led, d4_led0, d4_led1, gnd1, gnd2, gnd3, gnd4,
        gnd5, gnd6, gpin1, gpin2, green, green1, \green1* , \green2* ,
        green2_n, green_n, grn_a, grn_a_ylw_c, grn_c, grn_c_ylw_a,
        grna, grnc, iect, \ietn* , ietp, led2_a, led2_c, led_dual_a,
        led_dual_c1, led_dual_c2, \md0n* , md0p, \md1n* , md1p, \md2n* ,
        md2p, \md3n* , md3p, mdct0, mdct1, mdct2, mdct3, nc, \orange* ,
        \orange1* , \orange2* , p1, p10, p11, p12, p13, p14, p15, p16, p17,
        p18, p2, p3, p4, p5, p6, p7, p8, p9, rdn, rdp, shield1, shield2,
        shield3, shield4, shield_gnd1, shield_gnd2, tdn, tdp, tr0n,
        tr0p, tr1n, \tr1n* , tr1n_n, tr1p, tr2n, \tr2n* , tr2n_n, tr2p,
        tr3n, \tr3n* , tr3n_n, tr3p, \tr4n* , tr4n_n, tr4p, tx0n, tx0n0,
        tx0n1, tx0p, tx0p0, tx0p1, tx1n, tx1n0, tx1n1, tx1p, tx1p0,
        tx1p1, tx2n, tx2n0, tx2n1, tx2p, tx2p0, tx2p1, tx3n, tx3n0,
        tx3n1, tx3p, tx3p0, tx3p1, vcc, vcc0, vcc1, yela, yelc,
        yellow_n);
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    inout \17 ;
    inout \18 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout ch_gnd;
    inout ch_gnd0;
    inout ch_gnd1;
    inout com;
    inout ct0;
    inout ct1;
    inout ct2;
    inout ct3;
    inout ct4;
    inout d1_led;
    inout d1_led0;
    inout d1_led1;
    inout d2_led;
    inout d2_led0;
    inout d2_led1;
    inout d3_led;
    inout d3_led0;
    inout d3_led1;
    inout d4_led;
    inout d4_led0;
    inout d4_led1;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gpin1;
    inout gpin2;
    inout green;
    inout green1;
    inout \green1* ;
    inout \green2* ;
    inout green2_n;
    inout green_n;
    inout grn_a;
    inout grn_a_ylw_c;
    inout grn_c;
    inout grn_c_ylw_a;
    inout grna;
    inout grnc;
    inout iect;
    inout \ietn* ;
    inout ietp;
    inout led2_a;
    inout led2_c;
    inout led_dual_a;
    inout led_dual_c1;
    inout led_dual_c2;
    inout \md0n* ;
    inout md0p;
    inout \md1n* ;
    inout md1p;
    inout \md2n* ;
    inout md2p;
    inout \md3n* ;
    inout md3p;
    inout mdct0;
    inout mdct1;
    inout mdct2;
    inout mdct3;
    inout nc;
    inout \orange* ;
    inout \orange1* ;
    inout \orange2* ;
    inout p1;
    inout p10;
    inout p11;
    inout p12;
    inout p13;
    inout p14;
    inout p15;
    inout p16;
    inout p17;
    inout p18;
    inout p2;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;
    inout rdn;
    inout rdp;
    inout shield1;
    inout shield2;
    inout shield3;
    inout shield4;
    inout shield_gnd1;
    inout shield_gnd2;
    inout tdn;
    inout tdp;
    inout tr0n;
    inout tr0p;
    inout tr1n;
    inout \tr1n* ;
    inout tr1n_n;
    inout tr1p;
    inout tr2n;
    inout \tr2n* ;
    inout tr2n_n;
    inout tr2p;
    inout tr3n;
    inout \tr3n* ;
    inout tr3n_n;
    inout tr3p;
    inout \tr4n* ;
    inout tr4n_n;
    inout tr4p;
    inout tx0n;
    inout tx0n0;
    inout tx0n1;
    inout tx0p;
    inout tx0p0;
    inout tx0p1;
    inout tx1n;
    inout tx1n0;
    inout tx1n1;
    inout tx1p;
    inout tx1p0;
    inout tx1p1;
    inout tx2n;
    inout tx2n0;
    inout tx2n1;
    inout tx2p;
    inout tx2p0;
    inout tx2p1;
    inout tx3n;
    inout tx3n0;
    inout tx3n1;
    inout tx3p;
    inout tx3p0;
    inout tx3p1;
    inout vcc;
    inout vcc0;
    inout vcc1;
    inout yela;
    inout yelc;
    inout yellow_n;


    initial
        begin
        end

endmodule
