// generated by newgenasym  Tue Apr 17 14:42:29 2012


module q_pnp (b, c, c1, c2, e);
    inout b;
    inout c;
    inout c1;
    inout c2;
    inout e;


    initial
        begin
        end

endmodule
