-- generated by newgenasym Tue Apr 17 14:42:29 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity Q_PNP is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end Q_PNP;
