// generated by newgenasym  Mon Dec 21 12:18:11 2015


module u_levshft_txb0302 (a1, a2, b1, b2, gnd, oe, vcca, vccb);
    inout a1;
    inout a2;
    inout b1;
    inout b2;
    input gnd;
    inout oe;
    input vcca;
    input vccb;


    initial
        begin
        end

endmodule
