-- generated by newgenasym Mon Dec 21 12:18:11 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_levshft_txb0302 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	VCCA:      IN     STD_LOGIC;    
	VCCB:      IN     STD_LOGIC);
end u_levshft_txb0302;
