// generated by newgenasym  Tue Nov 07 18:29:32 2017


module u_mem_ee_i2c (a0, a1, a2, gnd, scl, sda, tp, vcc, wp);
    input a0;
    input a1;
    input a2;
    input gnd;
    input scl;
    inout sda;
    input tp;
    input vcc;
    input wp;


    initial
        begin
        end

endmodule
