-- generated by newgenasym Tue Nov 07 18:29:32 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_mem_ee_i2c is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	TP:        IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	WP:        IN     STD_LOGIC);
end u_mem_ee_i2c;
