// generated by newgenasym  Tue Dec 17 10:54:52 2002


module osc_4pin (en, gnd, out, vcc);
    input en;
    input gnd;
    output out;
    input vcc;


    initial
        begin
        end

endmodule
