-- generated by newgenasym Tue Dec 17 10:54:52 2002

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OSC_4PIN is
    port (    
	EN:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end OSC_4PIN;
