// generated by newgenasym  Mon Aug 05 10:56:38 2019


module u_levshft_3state (\1a1 , \1a2 , \1b1 , \1b2 , \1dir , \1oe* , \2a1 , \2a2 , \2b1 , \2b2 , \2dir , \2oe* ,
        a, a1, a2, a3, a4, a5, a6, a7, a8, b, b1, b2, b3, b4, b5, b6, b7, b8,
        dir, gnd, gnd1, gnd2, gnd3, in, nc, nc1, oe, \oe* , out, tgnd,
        thermpad, vcc, vcca, vccb, vccb1, vccb2);
    inout \1a1 ;
    inout \1a2 ;
    inout \1b1 ;
    inout \1b2 ;
    input \1dir ;
    input \1oe* ;
    inout \2a1 ;
    inout \2a2 ;
    inout \2b1 ;
    inout \2b2 ;
    input \2dir ;
    input \2oe* ;
    inout a;
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout b;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    input dir;
    input gnd;
    input gnd1;
    input gnd2;
    input gnd3;
    input in;
    input nc;
    output nc1;
    input oe;
    input \oe* ;
    output out;
    input tgnd;
    input thermpad;
    input vcc;
    input vcca;
    input vccb;
    input vccb1;
    input vccb2;


    initial
        begin
        end

endmodule
