// generated by newgenasym  Tue Jul 27 14:09:07 2010


module u_sw_ana_usb (\1a , \1b1 , \1b2 , \1dn , \1dp , \2a , \2b1 , \2b2 , \2dn , \2dp , comd1, comd2, dn,
        dp, en, fsd1, fsd2, gnd, hsd1, hsd1n, hsd1p, hsd2, hsd2n, hsd2p,
        in, \oe* , s, vcc);
    inout \1a ;
    inout \1b1 ;
    inout \1b2 ;
    inout \1dn ;
    inout \1dp ;
    inout \2a ;
    inout \2b1 ;
    inout \2b2 ;
    inout \2dn ;
    inout \2dp ;
    inout comd1;
    inout comd2;
    inout dn;
    inout dp;
    input en;
    inout fsd1;
    inout fsd2;
    input gnd;
    inout hsd1;
    inout hsd1n;
    inout hsd1p;
    inout hsd2;
    inout hsd2n;
    inout hsd2p;
    input in;
    input \oe* ;
    input s;
    input vcc;


    initial
        begin
        end

endmodule
