-- generated by newgenasym Tue Jul 27 14:09:07 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity U_SW_ANA_USB is
    port (    
	\1a\:      INOUT  STD_LOGIC;    
	\1b1\:     INOUT  STD_LOGIC;    
	\1b2\:     INOUT  STD_LOGIC;    
	\1dn\:     INOUT  STD_LOGIC;    
	\1dp\:     INOUT  STD_LOGIC;    
	\2a\:      INOUT  STD_LOGIC;    
	\2b1\:     INOUT  STD_LOGIC;    
	\2b2\:     INOUT  STD_LOGIC;    
	\2dn\:     INOUT  STD_LOGIC;    
	\2dp\:     INOUT  STD_LOGIC;    
	COMD1:     INOUT  STD_LOGIC;    
	COMD2:     INOUT  STD_LOGIC;    
	DN:        INOUT  STD_LOGIC;    
	DP:        INOUT  STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	FSD1:      INOUT  STD_LOGIC;    
	FSD2:      INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	HSD1:      INOUT  STD_LOGIC;    
	HSD1N:     INOUT  STD_LOGIC;    
	HSD1P:     INOUT  STD_LOGIC;    
	HSD2:      INOUT  STD_LOGIC;    
	HSD2N:     INOUT  STD_LOGIC;    
	HSD2P:     INOUT  STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC;    
	S:         IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end U_SW_ANA_USB;
