-- generated by newgenasym Tue Mar 11 12:41:32 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity virtual_short is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end virtual_short;
