-- generated by newgenasym Mon Jan 28 13:54:45 2002

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity R is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end R;
