-- generated by newgenasym Fri Mar 08 13:08:47 2002

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity C is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end C;
