// generated by newgenasym  Wed Jun 14 16:27:51 2017


module u_rst_mon (_mr, _pfo, _rst, _wdo, ct, enable, gnd, \input , \mr* , nc1, nc2,
        out1, out2, pfi, \pfo* , rst, \rst* , rst_in, rst_out, \rst_sen* ,
        sense, sense1, sense2, sense3, sense4, sense_out, srt, swt,
        vcc, vdd, vset0, vset1, vset2, wdi, wds);
    input _mr;
    output _pfo;
    output _rst;
    output _wdo;
    input ct;
    input enable;
    input gnd;
    output \input ;
    input \mr* ;
    output nc1;
    output nc2;
    output out1;
    output out2;
    input pfi;
    output \pfo* ;
    output rst;
    output \rst* ;
    input rst_in;
    input rst_out;
    output \rst_sen* ;
    input sense;
    input sense1;
    input sense2;
    input sense3;
    input sense4;
    output sense_out;
    input srt;
    input swt;
    input vcc;
    input vdd;
    input vset0;
    input vset1;
    input vset2;
    input wdi;
    input wds;


    initial
        begin
        end

endmodule
