-- generated by newgenasym Wed Jun 14 16:27:51 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_rst_mon is
    port (    
	\_mr\:     IN     STD_LOGIC;    
	\_pfo\:    OUT    STD_LOGIC;    
	\_rst\:    OUT    STD_LOGIC;    
	\_wdo\:    OUT    STD_LOGIC;    
	CT:        IN     STD_LOGIC;    
	ENABLE:    IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	INPUT:     OUT    STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	NC1:       OUT    STD_LOGIC;    
	NC2:       OUT    STD_LOGIC;    
	OUT1:      OUT    STD_LOGIC;    
	OUT2:      OUT    STD_LOGIC;    
	PFI:       IN     STD_LOGIC;    
	\pfo*\:    OUT    STD_LOGIC;    
	RST:       OUT    STD_LOGIC;    
	\rst*\:    OUT    STD_LOGIC;    
	RST_IN:    IN     STD_LOGIC;    
	RST_OUT:   IN     STD_LOGIC;    
	\rst_sen*\: OUT    STD_LOGIC;    
	SENSE:     IN     STD_LOGIC;    
	SENSE1:    IN     STD_LOGIC;    
	SENSE2:    IN     STD_LOGIC;    
	SENSE3:    IN     STD_LOGIC;    
	SENSE4:    IN     STD_LOGIC;    
	SENSE_OUT: OUT    STD_LOGIC;    
	SRT:       IN     STD_LOGIC;    
	SWT:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VSET0:     IN     STD_LOGIC;    
	VSET1:     IN     STD_LOGIC;    
	VSET2:     IN     STD_LOGIC;    
	WDI:       IN     STD_LOGIC;    
	WDS:       IN     STD_LOGIC);
end u_rst_mon;
