// generated by newgenasym  Tue Aug 27 15:55:09 2019


module u_ldo (adj, bias, en, en1, en2, epad, fb, fb1, fb2, gnd, gnd1, gnd2,
        gnd_13, gnd_3, in, in1_1, in1_2, in2_4, in2_5, in_1, in_2, nc,
        nc_1, nc_2, nr_ss1, nr_ss2, out, out1_14, out1_15, out2_11,
        out2_12, out_1, out_2, pad, pg, pg1, pg2, pok, shdn, ss,
        ss_ctrl1, ss_ctrl2, tp, vcntl, vctl, vin, vin1, vin2, vin3,
        vout, vout1, vout2, vout3);
    inout adj;
    input bias;
    input en;
    input en1;
    input en2;
    input epad;
    inout fb;
    input fb1;
    input fb2;
    input gnd;
    input gnd1;
    input gnd2;
    input gnd_13;
    input gnd_3;
    inout in;
    input in1_1;
    input in1_2;
    input in2_4;
    input in2_5;
    inout in_1;
    inout in_2;
    inout nc;
    inout nc_1;
    inout nc_2;
    inout nr_ss1;
    inout nr_ss2;
    inout out;
    input out1_14;
    input out1_15;
    input out2_11;
    input out2_12;
    inout out_1;
    inout out_2;
    input pad;
    output pg;
    output pg1;
    output pg2;
    output pok;
    input shdn;
    input ss;
    input ss_ctrl1;
    input ss_ctrl2;
    input tp;
    input vcntl;
    input vctl;
    input vin;
    input vin1;
    input vin2;
    input vin3;
    input vout;
    input vout1;
    input vout2;
    input vout3;


    initial
        begin
        end

endmodule
