// generated by newgenasym  Tue Nov 29 16:55:27 2016


module d_esd_diffpair (\1 , \1a , \1b , \2a , \2b , \3 , \3a , \3b , \4 , \4a , \4b , \6 , a, b, ch1, ch2, ch3, ch4,
        d1n, d1p, d2n, d2p, dm, dn, dp, gnd, gnd1, gnd2, gnd3, gnd4, id,
        in_1n, in_1p, in_2n, in_2p, in_3n, in_3p, in_4n, in_4p, line1,
        line2, line3, nc, nc1, nc2, nc3, nc4, nc_ch1, nc_ch2, nc_ch3,
        nc_ch4, out_1n, out_1p, out_2n, out_2p, out_3n, out_3p,
        out_4n, out_4p, pwr, pwr1, tp, vbus);
    inout \1 ;
    inout \1a ;
    inout \1b ;
    inout \2a ;
    inout \2b ;
    inout \3 ;
    inout \3a ;
    inout \3b ;
    inout \4 ;
    inout \4a ;
    inout \4b ;
    inout \6 ;
    inout a;
    inout b;
    inout ch1;
    inout ch2;
    inout ch3;
    inout ch4;
    inout d1n;
    inout d1p;
    inout d2n;
    inout d2p;
    inout dm;
    inout dn;
    inout dp;
    input gnd;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    inout id;
    inout in_1n;
    inout in_1p;
    inout in_2n;
    inout in_2p;
    inout in_3n;
    inout in_3p;
    inout in_4n;
    inout in_4p;
    inout line1;
    inout line2;
    inout line3;
    inout nc;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc_ch1;
    inout nc_ch2;
    inout nc_ch3;
    inout nc_ch4;
    inout out_1n;
    inout out_1p;
    inout out_2n;
    inout out_2p;
    inout out_3n;
    inout out_3p;
    inout out_4n;
    inout out_4p;
    input pwr;
    input pwr1;
    input tp;
    inout vbus;


    initial
        begin
        end

endmodule
