// generated by newgenasym  Thu Dec 13 14:46:31 2018


module u_vreg_5pin (adj, bias, byp, ctrl, \eco* , en, \en* , fb, gnd, gnd1, gnd2, gnd3,
        gnd4, gnd_1, gnd_2, in, nc, nc1, nc2, nc3, out, out1, out2, out3,
        out4, \output , sense, \shdn* , tab, th, thrmgnd, vcntl5, vcntl6,
        vcntl7, vcntl8, vdd1, vdd2, vin, vout, vref);
    inout adj;
    inout bias;
    inout byp;
    inout ctrl;
    inout \eco* ;
    inout en;
    inout \en* ;
    inout fb;
    input gnd;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd_1;
    input gnd_2;
    inout in;
    inout nc;
    inout nc1;
    inout nc2;
    inout nc3;
    inout out;
    inout out1;
    inout out2;
    inout out3;
    inout out4;
    input \output ;
    inout sense;
    inout \shdn* ;
    inout tab;
    input th;
    input thrmgnd;
    inout vcntl5;
    inout vcntl6;
    inout vcntl7;
    inout vcntl8;
    input vdd1;
    input vdd2;
    inout vin;
    inout vout;
    inout vref;


    initial
        begin
        end

endmodule
