-- generated by newgenasym Thu Dec 13 14:46:31 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_vreg_5pin is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	BIAS:      INOUT  STD_LOGIC;    
	BYP:       INOUT  STD_LOGIC;    
	CTRL:      INOUT  STD_LOGIC;    
	\eco*\:    INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	\en*\:     INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	GND_1:     IN     STD_LOGIC;    
	GND_2:     IN     STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	OUT3:      INOUT  STD_LOGIC;    
	OUT4:      INOUT  STD_LOGIC;    
	OUTPUT:    IN     STD_LOGIC;    
	SENSE:     INOUT  STD_LOGIC;    
	\shdn*\:   INOUT  STD_LOGIC;    
	TAB:       INOUT  STD_LOGIC;    
	TH:        IN     STD_LOGIC;    
	THRMGND:   IN     STD_LOGIC;    
	VCNTL5:    INOUT  STD_LOGIC;    
	VCNTL6:    INOUT  STD_LOGIC;    
	VCNTL7:    INOUT  STD_LOGIC;    
	VCNTL8:    INOUT  STD_LOGIC;    
	VDD1:      IN     STD_LOGIC;    
	VDD2:      IN     STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end u_vreg_5pin;
