// generated by newgenasym  Fri Jan 04 15:18:21 2019


module d_esd (\1 , \1_15 , \1a , \1c , \2 , \2_24 , \2a , \2c , \3 , \4 , \5 , \6 , gnd, gnd1, gnd12,
        gnd14, gnd16, gnd18, gnd19, gnd2, gnd20, gnd21, io_1, io_2,
        io_3, io_4, io_5, io_6, line1, line10, line11, line13, line15,
        line17, line2, line3, line4, line5, line6, line7, line8,
        line9, p1, p2, p3, pwr);
    inout \1 ;
    inout \1_15 ;
    inout \1a ;
    inout \1c ;
    inout \2 ;
    inout \2_24 ;
    inout \2a ;
    inout \2c ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    input gnd;
    input gnd1;
    input gnd12;
    input gnd14;
    input gnd16;
    input gnd18;
    input gnd19;
    input gnd2;
    input gnd20;
    input gnd21;
    inout io_1;
    inout io_2;
    inout io_3;
    inout io_4;
    inout io_5;
    inout io_6;
    inout line1;
    input line10;
    input line11;
    input line13;
    input line15;
    input line17;
    inout line2;
    inout line3;
    inout line4;
    input line5;
    input line6;
    input line7;
    input line8;
    input line9;
    inout p1;
    inout p2;
    inout p3;
    input pwr;


    initial
        begin
        end

endmodule
