-- generated by newgenasym Wed Jul 31 08:51:52 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity d_zener is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end d_zener;
