// generated by newgenasym  Mon May 13 17:40:20 2019


module mounting_hole (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \1a , \1b , \2 , \2a , \2b , \3 , \4 , \5 , \6 , \7 , \8 , \9 ,
        gnd, pad);
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    inout \1a ;
    inout \1b ;
    inout \2 ;
    inout \2a ;
    inout \2b ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout gnd;
    inout pad;


    initial
        begin
        end

endmodule
