-- generated by newgenasym Mon May 13 17:40:20 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mounting_hole is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\10\:      INOUT  STD_LOGIC;    
	\11\:      INOUT  STD_LOGIC;    
	\12\:      INOUT  STD_LOGIC;    
	\13\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\15\:      INOUT  STD_LOGIC;    
	\16\:      INOUT  STD_LOGIC;    
	\1a\:      INOUT  STD_LOGIC;    
	\1b\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\2a\:      INOUT  STD_LOGIC;    
	\2b\:      INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC;    
	\9\:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC);
end mounting_hole;
