// generated by newgenasym  Wed Jun 05 09:15:43 2019


module led (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \16 , \17 , \18 , \1a , \2 , \2a , \3 , \3a , \4 , \4a , \5 , \6 , \7 ,
        \8 , \9 , a, a1, a2, a3, a5, b, ba, bc, c, c0, c1, c2, c3, c4, c6, ca1, ca2,
        d, dp, e, f, g, ga, gc, k, nc, r, ra, rc, ya, yc, za);
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \16 ;
    inout \17 ;
    inout \18 ;
    inout \1a ;
    inout \2 ;
    inout \2a ;
    inout \3 ;
    inout \3a ;
    inout \4 ;
    inout \4a ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout a;
    inout a1;
    inout a2;
    inout a3;
    inout a5;
    inout b;
    inout ba;
    inout bc;
    inout c;
    inout c0;
    inout c1;
    inout c2;
    inout c3;
    inout c4;
    inout c6;
    inout ca1;
    inout ca2;
    inout d;
    inout dp;
    inout e;
    inout f;
    inout g;
    inout ga;
    inout gc;
    inout k;
    inout nc;
    inout r;
    inout ra;
    inout rc;
    inout ya;
    inout yc;
    inout za;


    initial
        begin
        end

endmodule
