-- generated by newgenasym Wed Sep 24 14:58:28 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity D_3PIN_CC is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	CC:        INOUT  STD_LOGIC);
end D_3PIN_CC;
