// generated by newgenasym  Tue Apr 23 17:39:12 2019


module l (\1 , \1a , \1b , \2 , \2a , \2b , \3 , \4 );
    inout \1 ;
    inout \1a ;
    inout \1b ;
    inout \2 ;
    inout \2a ;
    inout \2b ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
