-- generated by newgenasym Tue Apr 23 17:39:12 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\1a\:      INOUT  STD_LOGIC;    
	\1b\:      INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\2a\:      INOUT  STD_LOGIC;    
	\2b\:      INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end l;
