// generated by newgenasym  Wed Jul 31 09:23:55 2019


module d_schottky (a, a1, a2, k, k1, k2);
    inout a;
    inout a1;
    inout a2;
    inout k;
    inout k1;
    inout k2;


    initial
        begin
        end

endmodule
