-- generated by newgenasym Wed Jul 31 09:23:55 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity d_schottky is
    port (    
	A:         INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC;    
	K1:        INOUT  STD_LOGIC;    
	K2:        INOUT  STD_LOGIC);
end d_schottky;
