// generated by newgenasym  Mon Jun 19 11:47:54 2017


module u_pwr_sw_ul (en, gnd, in, \oc* , out);
    input en;
    input gnd;
    input in;
    output \oc* ;
    input out;


    initial
        begin
        end

endmodule
