-- generated by newgenasym Mon Jun 19 11:47:54 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_pwr_sw_ul is
    port (    
	EN:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\oc*\:     OUT    STD_LOGIC;    
	\out\:     IN     STD_LOGIC);
end u_pwr_sw_ul;
