// generated by newgenasym  Thu Feb 08 10:32:36 2018


module c_pol (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
