-- generated by newgenasym Thu Feb 08 10:32:36 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c_pol is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end c_pol;
