// generated by newgenasym  Tue Aug 02 15:07:52 2016


module mec_standoff (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
