-- generated by newgenasym Tue Aug 02 15:07:52 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mec_standoff is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end mec_standoff;
