// generated by newgenasym  Wed Jan 09 07:00:53 2019


module q_fet_n_enh (bg, d, d1, d1_1, d1_2, d1_d2, d1a, d1b, d2, d2a, d2b, d3, d4, d5,
        g, g1, g2, pgnd, s, s1, s1_0, s1_1, s1_d2_1, s1_d2_2, s1_d2_3,
        s2, s2_0, s2_1, s3, s4, s5, tg, tgr, vin1, vsw1, vsw2, vsw3);
    inout bg;
    inout d;
    inout d1;
    inout d1_1;
    inout d1_2;
    inout d1_d2;
    inout d1a;
    inout d1b;
    inout d2;
    inout d2a;
    inout d2b;
    inout d3;
    inout d4;
    inout d5;
    inout g;
    inout g1;
    inout g2;
    input pgnd;
    inout s;
    inout s1;
    inout s1_0;
    inout s1_1;
    inout s1_d2_1;
    inout s1_d2_2;
    inout s1_d2_3;
    inout s2;
    inout s2_0;
    inout s2_1;
    inout s3;
    inout s4;
    inout s5;
    inout tg;
    inout tgr;
    inout vin1;
    inout vsw1;
    inout vsw2;
    inout vsw3;


    initial
        begin
        end

endmodule
