-- generated by newgenasym Wed Jan 09 07:00:53 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity q_fet_n_enh is
    port (    
	BG:        INOUT  STD_LOGIC;    
	D:         INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D1_1:      INOUT  STD_LOGIC;    
	D1_2:      INOUT  STD_LOGIC;    
	D1_D2:     INOUT  STD_LOGIC;    
	D1A:       INOUT  STD_LOGIC;    
	D1B:       INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D2A:       INOUT  STD_LOGIC;    
	D2B:       INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	D4:        INOUT  STD_LOGIC;    
	D5:        INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	G1:        INOUT  STD_LOGIC;    
	G2:        INOUT  STD_LOGIC;    
	PGND:      IN     STD_LOGIC;    
	S:         INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	S1_0:      INOUT  STD_LOGIC;    
	S1_1:      INOUT  STD_LOGIC;    
	S1_D2_1:   INOUT  STD_LOGIC;    
	S1_D2_2:   INOUT  STD_LOGIC;    
	S1_D2_3:   INOUT  STD_LOGIC;    
	S2:        INOUT  STD_LOGIC;    
	S2_0:      INOUT  STD_LOGIC;    
	S2_1:      INOUT  STD_LOGIC;    
	S3:        INOUT  STD_LOGIC;    
	S4:        INOUT  STD_LOGIC;    
	S5:        INOUT  STD_LOGIC;    
	TG:        INOUT  STD_LOGIC;    
	TGR:       INOUT  STD_LOGIC;    
	VIN1:      INOUT  STD_LOGIC;    
	VSW1:      INOUT  STD_LOGIC;    
	VSW2:      INOUT  STD_LOGIC;    
	VSW3:      INOUT  STD_LOGIC);
end q_fet_n_enh;
