// generated by newgenasym  Mon Oct 14 11:45:15 2019


module con_usb3 (cc, cc1, cc2, d1_n, d1_p, d2_n, d2_p, d_n, d_p, dn, dn0, dn1, dp,
        dp0, dp1, gnd1, gnd2, gnd3, gnd4, gnd5, gnd6, gnd7, id, mp1, mp2,
        mp3, mp4, mt1, mt2, mt3, mt4, mt5, mt6, mt7, mt8, mt9, open_d_n,
        open_d_p, rx_n, rx_p, sbu1, sbu2, sh1, sh10, sh11, sh12, sh13,
        sh14, sh2, sh3, sh4, sh5, sh6, sh7, sh8, sh9, ssrx1_n, ssrx1_p,
        ssrx2_n, ssrx2_p, ssrxn, ssrxn0, ssrxn1, ssrxp, ssrxp0,
        ssrxp1, sstx1_n, sstx1_p, sstx2_n, sstx2_p, sstxn, sstxn0,
        sstxn1, sstxp, sstxp0, sstxp1, tab1, tab2, tab3, tab4, tx_n,
        tx_p, vbus, vbus0, vbus1, vbus2, vbus3, vbus4, vconn);
    inout cc;
    inout cc1;
    inout cc2;
    inout d1_n;
    inout d1_p;
    inout d2_n;
    inout d2_p;
    inout d_n;
    inout d_p;
    inout dn;
    inout dn0;
    inout dn1;
    inout dp;
    inout dp0;
    inout dp1;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout id;
    inout mp1;
    inout mp2;
    inout mp3;
    inout mp4;
    inout mt1;
    inout mt2;
    inout mt3;
    inout mt4;
    inout mt5;
    inout mt6;
    inout mt7;
    inout mt8;
    inout mt9;
    inout open_d_n;
    inout open_d_p;
    inout rx_n;
    inout rx_p;
    inout sbu1;
    inout sbu2;
    inout sh1;
    inout sh10;
    inout sh11;
    inout sh12;
    inout sh13;
    inout sh14;
    inout sh2;
    inout sh3;
    inout sh4;
    inout sh5;
    inout sh6;
    inout sh7;
    inout sh8;
    inout sh9;
    inout ssrx1_n;
    inout ssrx1_p;
    inout ssrx2_n;
    inout ssrx2_p;
    inout ssrxn;
    inout ssrxn0;
    inout ssrxn1;
    inout ssrxp;
    inout ssrxp0;
    inout ssrxp1;
    inout sstx1_n;
    inout sstx1_p;
    inout sstx2_n;
    inout sstx2_p;
    inout sstxn;
    inout sstxn0;
    inout sstxn1;
    inout sstxp;
    inout sstxp0;
    inout sstxp1;
    inout tab1;
    inout tab2;
    inout tab3;
    inout tab4;
    inout tx_n;
    inout tx_p;
    inout vbus;
    inout vbus0;
    inout vbus1;
    inout vbus2;
    inout vbus3;
    inout vbus4;
    inout vconn;


    initial
        begin
        end

endmodule
