// generated by newgenasym  Wed Jan 03 10:47:33 2018


module u_cpu_efm8sb1 (epad, gnd1, gnd2, p0_0, p0_1, p0_2, p0_3, p0_4, p0_5, p0_6,
        p0_7, p1_0, p1_1, p1_2, p1_3, p1_5, p1_6, p1_7, p2_7_c2d, \rst* ,
        vdd);
    input epad;
    input gnd1;
    input gnd2;
    inout p0_0;
    inout p0_1;
    inout p0_2;
    inout p0_3;
    inout p0_4;
    inout p0_5;
    inout p0_6;
    inout p0_7;
    inout p1_0;
    inout p1_1;
    inout p1_2;
    inout p1_3;
    inout p1_5;
    inout p1_6;
    inout p1_7;
    inout p2_7_c2d;
    inout \rst* ;
    input vdd;


    initial
        begin
        end

endmodule
