-- generated by newgenasym Wed Jan 03 10:47:33 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity u_cpu_efm8sb1 is
    port (    
	EPAD:      IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	P0_0:      INOUT  STD_LOGIC;    
	P0_1:      INOUT  STD_LOGIC;    
	P0_2:      INOUT  STD_LOGIC;    
	P0_3:      INOUT  STD_LOGIC;    
	P0_4:      INOUT  STD_LOGIC;    
	P0_5:      INOUT  STD_LOGIC;    
	P0_6:      INOUT  STD_LOGIC;    
	P0_7:      INOUT  STD_LOGIC;    
	P1_0:      INOUT  STD_LOGIC;    
	P1_1:      INOUT  STD_LOGIC;    
	P1_2:      INOUT  STD_LOGIC;    
	P1_3:      INOUT  STD_LOGIC;    
	P1_5:      INOUT  STD_LOGIC;    
	P1_6:      INOUT  STD_LOGIC;    
	P1_7:      INOUT  STD_LOGIC;    
	P2_7_C2D:  INOUT  STD_LOGIC;    
	\rst*\:    INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end u_cpu_efm8sb1;
