// generated by newgenasym  Thu Aug 23 12:07:22 2018


module con_fpc_15 (\1 , \10 , \11 , \12 , \13 , \14 , \15 , \2 , \3 , \4 , \5 , \6 , \7 , \8 , \9 , pin1, pin10, pin11,
        pin12, pin13, pin14, pin15, pin16, pin17, pin18, pin19, pin2,
        pin20, pin21, pin22, pin23, pin24, pin25, pin26, pin27, pin28,
        pin29, pin3, pin30, pin4, pin5, pin6, pin7, pin8, pin9);
    inout \1 ;
    inout \10 ;
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \15 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout \7 ;
    inout \8 ;
    inout \9 ;
    inout pin1;
    inout pin10;
    inout pin11;
    inout pin12;
    inout pin13;
    inout pin14;
    inout pin15;
    inout pin16;
    inout pin17;
    inout pin18;
    inout pin19;
    inout pin2;
    inout pin20;
    inout pin21;
    inout pin22;
    inout pin23;
    inout pin24;
    inout pin25;
    inout pin26;
    inout pin27;
    inout pin28;
    inout pin29;
    inout pin3;
    inout pin30;
    inout pin4;
    inout pin5;
    inout pin6;
    inout pin7;
    inout pin8;
    inout pin9;


    initial
        begin
        end

endmodule
