// generated by newgenasym  Mon Jan 26 14:32:31 2015


module con_usb (dn, dn1, dn2, dp, dp1, dp2, gnd, gnd1, gnd2, id, mt1, mt2, rx_n,
        rx_p, sh1, sh2, sh3, sh4, sh5, sh6, tx_n, tx_p, vbus, vbus1,
        vbus2);
    inout dn;
    inout dn1;
    inout dn2;
    inout dp;
    inout dp1;
    inout dp2;
    inout gnd;
    inout gnd1;
    inout gnd2;
    inout id;
    inout mt1;
    inout mt2;
    inout rx_n;
    inout rx_p;
    inout sh1;
    inout sh2;
    inout sh3;
    inout sh4;
    inout sh5;
    inout sh6;
    inout tx_n;
    inout tx_p;
    inout vbus;
    inout vbus1;
    inout vbus2;


    initial
        begin
        end

endmodule
