-- generated by newgenasym Mon Jan 26 14:32:31 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con_usb is
    port (    
	DN:        INOUT  STD_LOGIC;    
	DN1:       INOUT  STD_LOGIC;    
	DN2:       INOUT  STD_LOGIC;    
	DP:        INOUT  STD_LOGIC;    
	DP1:       INOUT  STD_LOGIC;    
	DP2:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	ID:        INOUT  STD_LOGIC;    
	MT1:       INOUT  STD_LOGIC;    
	MT2:       INOUT  STD_LOGIC;    
	RX_N:      INOUT  STD_LOGIC;    
	RX_P:      INOUT  STD_LOGIC;    
	SH1:       INOUT  STD_LOGIC;    
	SH2:       INOUT  STD_LOGIC;    
	SH3:       INOUT  STD_LOGIC;    
	SH4:       INOUT  STD_LOGIC;    
	SH5:       INOUT  STD_LOGIC;    
	SH6:       INOUT  STD_LOGIC;    
	TX_N:      INOUT  STD_LOGIC;    
	TX_P:      INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC;    
	VBUS1:     INOUT  STD_LOGIC;    
	VBUS2:     INOUT  STD_LOGIC);
end con_usb;
